# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Proof of concept - AGA+CT
description: >- # this means to ignore newlines until "baseurl:"
  A prototype showing possible design approach
baseurl: "/betaga" # the subpath of your site, e.g. /blog
url: "https://jamesfehon-dta.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: _collections
collections:
  capabilities:
    output: true
    permalink: /capability/:path/
  resources:
    output: true
    permalink: /resource/:path/

defaults:
  - scope:
      path: "assets" # Folder name
    values:
      robots: noindex
      site-search: false

# plugins:
#   - jekyll-lunr-js-custom-search

# lunr_settings:
#   ref: url # or: id
#   atozsortfield: title
#   collections:
#     - capabilities
#   fields:
#     - searchfield: title
#       boost: 15
#       jekyllfields:
#         - title
#     - searchfield: description
#       boost: 5
#       markdown: true
#       jekyllfields:
#         - description
#     - searchfield: type
#       boost: 0
#       facetfield: true
#       jekyllfields:
#         - type
#     - searchfield: content
#       boost: 3
#       markdown: true
#       jekyllfields:
#         - content
#   displayfields:
#     - field: title
#       headerfield: true
#     - field: content
#       contentfield: true
#       truncate: 50
#     - field: description
#       label: Description
#     - field: type
#       label: Type
#   fuzzysearchfields: [title, description, content]


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - search-prebuild
  - node_modules
  - package.json
  - package-lock.json

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
